site_name: Mr. Network Documentation
site_description: Documentation for mrnet
copyright: Built by The Materials Project

theme:
  name: 'material'

nav:
  - Home: index.md

site_url: https://materialsproject.github.io/mrnet/
repo_url: https://github.com/materialsproject/mrnet/

markdown_extensions:
  - pymdownx.tabbed
  - admonition
  - codehilite
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: true

plugins:
  - search
  - minify
  - mkdocstrings